// <auto-generated />
namespace UML_proj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adding_recei_forms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_recei_forms));
        
        string IMigrationMetadata.Id
        {
            get { return "201805271515273_adding_recei_forms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
