//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UML_proj.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IT_PROJEKTASEntities : DbContext
    {
        public IT_PROJEKTASEntities()
            : base("name=IT_PROJEKTASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Newsletter> Newsletters { get; set; }
        public virtual DbSet<Newsletter_entry> Newsletter_entry { get; set; }
        public virtual DbSet<NullObjectOwner> NullObjectOwners { get; set; }
        public virtual DbSet<Owner_person_adapter> Owner_person_adapter { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Product_in_shop> Product_in_shop { get; set; }
        public virtual DbSet<regUser> regUsers { get; set; }
        public virtual DbSet<Search_parameters> Search_parameters { get; set; }
        public virtual DbSet<Seller> Sellers { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<Subscribed_newsletter> Subscribed_newsletter { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Unclassified_pictures> Unclassified_pictures { get; set; }
    }
}
