//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UML_proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newsletter_entry
    {
        public string state { get; set; }
        public int id_Newsletter_entry { get; set; }
        public int fk_Sellerid_Person { get; set; }
        public int fk_Userid_Person { get; set; }
        public int fk_Newsletterid_Newsletter { get; set; }
        public int fk_Newsletterid_Newsletter1 { get; set; }

        public void insert(Newsletter_entry[] obj)
        {
            IT_PROJEKTASEntities db = new IT_PROJEKTASEntities();
            for (int i = 0; i < obj.Length; i++)
            {
                db.Newsletter_entry.Add(obj[i]);
            }
        }
        public void insert(Newsletter_entry obj)
        {
            IT_PROJEKTASEntities db = new IT_PROJEKTASEntities();
            db.Newsletter_entry.Add(obj);
        }

        public virtual Newsletter Newsletter { get; set; }
        public virtual Newsletter Newsletter1 { get; set; }
        public virtual regUser regUser { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
