//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UML_proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner_person_adapter
    {
        public int id_Owner_person_adapter { get; set; }
        public int fk_Personid_Person { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
