//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UML_proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Newsletters = new HashSet<Newsletter>();
            this.Owner_person_adapter = new HashSet<Owner_person_adapter>();
            this.Subscribed_newsletter = new HashSet<Subscribed_newsletter>();
            this.Shops = new HashSet<Shop>();
        }
    
        public string Vardas { get; set; }
        public string Pavarde { get; set; }
        public string El_Paštas { get; set; }
        public string Slaptažodis { get; set; }
        public string Discord_Id { get; set; }
        public Nullable<System.DateTime> Paskutinis_prisijungimas { get; set; }
        public Nullable<System.DateTime> Registravimosi_data { get; set; }
        public string Busena { get; set; }
        public int id_Person { get; set; }
    
        public virtual Admin Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Newsletter> Newsletters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Owner_person_adapter> Owner_person_adapter { get; set; }
        public virtual regUser regUser { get; set; }
        public virtual Seller Seller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscribed_newsletter> Subscribed_newsletter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shops { get; set; }
    }
}
