//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UML_proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class regUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public regUser()
        {
            this.Newsletter_entry = new HashSet<Newsletter_entry>();
            this.Subscribed_newsletter = new HashSet<Subscribed_newsletter>();
        }
    
        public string Salis { get; set; }
        public string Miestas { get; set; }
        public string Rajonas { get; set; }
        public string Gatve { get; set; }
        public string Buto_numeris { get; set; }
        public Nullable<int> Gimimo_metai { get; set; }
        public string Gimimo_menesis { get; set; }
        public Nullable<int> Gimimo_diena { get; set; }
        public int id_Person { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Newsletter_entry> Newsletter_entry { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscribed_newsletter> Subscribed_newsletter { get; set; }
    }
}
