//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UML_proj.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Subscribed_newsletter
    {
        IT_PROJEKTASEntities db = new IT_PROJEKTASEntities();
        public string receit_form { get; set; }
        public int id { get; set; }
        public int fk_subscriber_id { get; set; }
        public int fk_newsletter_id { get; set; }

        public IEnumerable<Subscribed_newsletter> select(int id, bool newsletter)
        {
            // newsletter == true : all subs of this newsletter. false = a single person's sub list
            
            if (newsletter)
            {
                var dataset = db.Subscribed_newsletter
                    .Where(x => x.fk_newsletter_id == id)
                    .Select(x => new 
                    {
                        receit_form = x.receit_form,
                        id = x.id,
                        fk_subscriber_id = x.fk_subscriber_id,
                        fk_newsletter_id = x.fk_newsletter_id
                    }).ToList().Select(x => new Subscribed_newsletter
                    {
                        receit_form = x.receit_form,
                        id = x.id,
                        fk_subscriber_id = x.fk_subscriber_id,
                        fk_newsletter_id = x.fk_newsletter_id
                    });

                return dataset;
            }
            else
            {
                var dataset = db.Subscribed_newsletter
                    .Where(x => x.fk_subscriber_id == id)
                    .Select(x => new 
                    {
                        receit_form = x.receit_form,
                        id = x.id,
                        fk_subscriber_id = x.fk_subscriber_id,
                        fk_newsletter_id = x.fk_newsletter_id
                    }).ToList().Select(x => new Subscribed_newsletter
                    {
                        receit_form = x.receit_form,
                        id = x.id,
                        fk_subscriber_id = x.fk_subscriber_id,
                        fk_newsletter_id = x.fk_newsletter_id
                    });
                return dataset;
            }
        }

        public virtual Newsletter Newsletter { get; set; }
        public virtual Person Person { get; set; }
    }
}
