//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UML_proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribed_newsletter
    {
        public string Pateikimo_forma { get; set; }
        public int id_Subscribed_newsletter { get; set; }
        public int fk_Userid_Person { get; set; }
        public int fk_Newsletterid_Newsletter { get; set; }
        public int fk_Personid_Person { get; set; }
        public int fk_Personid_Person1 { get; set; }
    
        public virtual Newsletter Newsletter { get; set; }
        public virtual Person Person { get; set; }
        public virtual regUser regUser { get; set; }
    }
}
