//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UML_proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unclassified_pictures
    {
        public Nullable<System.DateTime> ikelimo_data { get; set; }
        public int id_Unclassified_pictures { get; set; }
        public int fk_Search_parametersid_Search_parameters { get; set; }
    
        public virtual Search_parameters Search_parameters { get; set; }
    }
}
